### ISSUE TITLE
How to implement this library? 

### ISSUE THREAD

**Issue by Monabr** [cotrin8672/kotlin-firebase-js#1]
Hi.

How to use your library?

Please update README.

**Comment by cotrin8672** [comment]
This library is hosted on mavenCentral, though,
This library has not been maintained for a long time now.
You can use this [repository](https://github.com/GitLiveApp/firebase-kotlin-sdk) instead. It supports a variety of targets besides js and should be upward compatible with this library.

**Comment by Monabr** [comment]
@cotrin8672 I created the issue there https://github.com/GitLiveApp/firebase-kotlin-sdk/issues/659

I can't figure out how to use it in backend project.

I think sdk your are linked in mostly for web but not for node.js backend. Isn't it?

**Comment by cotrin8672** [comment]
I don't know that much about Firebase, so I apologise if I'm missing the point.
Are you using Kotlin/JS to build a Node.js-based backend? If so, don't you need a Kotlin/JS wrapper for the Firebase JS Admin SDK?

**Comment by Monabr** [comment]
@cotrin8672 Yes, my plan now is to translate from Kotlin to Node.js. The parts I'm missing are entry points like "onCall" and Admin SDK

**Comment by cotrin8672** [comment]
My library probably does not support the Firebase Admin SDK either. A wrapper could be developed separately, but this would be time-consuming.

**Comment by Monabr** [comment]
@cotrin8672 I have found this https://github.com/ChrisKruegerDev/kotlin-firebase-admin but its from 2021

**Comment by cotrin8672** [comment]
It would take significant time to develop the Firebase Admin SDK wrapper, so I would ask for compensation for the development work. However, once the library is completed, I plan to make it available on Maven Central so others can also benefit from it.

I also wanted to mention that I am still a student and need to cover my own tuition fees. Given that, it would be really helpful to receive compensation for the time I would spend on this project, as it would require me to dedicate time outside of my studies. If you’re open to this, we can further discuss the development timeline, feature scope, and the cost involved.

**Comment by cotrin8672** [comment]
There are currently no plans to support the Firebase Admin SDK as this would take a significant amount of time. However, if you are willing to provide remuneration, we would be happy to undertake the development.
